### ISSUE TITLE
Social Icons not visible

### ISSUE THREAD

**Issue by huteck** [pmoreno-rodriguez/grav-theme-future2021#34]
The Social Icons are not visible while being in html code (see picture) but with a size of 0. (Both in Sidebar mode as well as in normal footer). I also tried to add the social icon in the header to cross-check but there one out of the two sizes is 0 as well.
This is on a fresh Grav installation without any plugins or changes to the template.

![image](https://user-images.githubusercontent.com/117048767/223561560-46873ab2-4426-4286-a11e-353ab2025749.png)

**Comment by pmoreno-rodriguez** [comment]
Could you send an online version, where can I see it?

**Comment by pmoreno-rodriguez** [comment]
I've just install a fresh Grav in my localhost folder, wit composer and I've installed the Future2021 with gpm. This is my future2021.yaml (previously I've copied it from theme folder to config/themes folder):
```
enabled: true
production-mode: false
enable_social: true
social:
  -
    name: Twitter
    url: 'https://www.twitter.com'
    icon: 'fa fa-twitter'
  -
    name: Facebook
    url: 'https://www.facebook.com'
    icon: 'fa fa-facebook'
  -
    name: Instagram
    url: 'https://www.instagram.com'
    icon: 'fa fa-instagram'
```
All works fine

![future2021_footer](https://user-images.githubusercontent.com/60596353/223839870-bcf4e784-ac6d-49ba-8d32-8693233d5311.jpg)

Have you cleared cache?
