### ISSUE TITLE
Remove the menu 'hamburger' from the top bar

### ISSUE THREAD

**Issue by l0rddarkf0rce** [pmoreno-rodriguez/grav-theme-future2021#57]
I have looked everywhere in the settings and cannot find anyway to completely remove the menu from displaying. I am not using and it shows as empty, but I want to completely remove it. Is this possible?

**Comment by pmoreno-rodriguez** [comment]
Hello.
The hamburger menu is designed for mobile devices. It displays all the menu items that appear on the desktop and other plugins such as taxonomy, archives, etc.
If you do not use any of them, it may be necessary to adjust a variable that indicates that this menu is not displayed, otherwise it makes no sense to hide it.

**Comment by l0rddarkf0rce** [comment]
> If you do not use any of them, it may be necessary to adjust a variable that indicates that this menu is not displayed, otherwise it makes no sense to hide it.

Which variable should I need to hide it? Many thanks

**Comment by pmoreno-rodriguez** [comment]
In `blueprints.yaml` (theme root folder), you may add this:
```
show_hamburguer_menu:
          type: toggle
          label: Show hamburguer menu
          highlight: 1
          default: 1
          options:
            1: PLUGIN_ADMIN.ENABLED
            0: PLUGIN_ADMIN.DISABLED
          validate:
            type: bool
```
Then, in `partials\header.html.twig` near from line 40, you need to add something like this:
```
{% if theme_var('show_hamburguer_menu')|defined(true) %}
        <li class="menu">
          <a class="fa-bars" href="#menu">Menu</a>
        </li>
{% endif %}
```
